//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Crm { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Email { get; set; }
        public Nullable<int> AtendePorConvenio { get; set; }
        public Nullable<int> TemClinica { get; set; }
        public string WebsiteBlog { get; set; }
        public int CidadeId { get; set; }
        public int EspecialidadeId { get; set; }
    
        public virtual Especialidade Especialidade { get; set; }
        public virtual Cidade Cidade { get; set; }
    }
}
